//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string ActionPlaceHasTicketError {
            get {
                return ResourceManager.GetString("ActionPlaceHasTicketError", resourceCulture);
            }
        }
        
        public static string ActionPlaceIsNull {
            get {
                return ResourceManager.GetString("ActionPlaceIsNull", resourceCulture);
            }
        }
        
        public static string ActionPlaceNameRequired {
            get {
                return ResourceManager.GetString("ActionPlaceNameRequired", resourceCulture);
            }
        }
        
        public static string ActionPlaceNotFound {
            get {
                return ResourceManager.GetString("ActionPlaceNotFound", resourceCulture);
            }
        }
        
        public static string ActionPlaceSelectError {
            get {
                return ResourceManager.GetString("ActionPlaceSelectError", resourceCulture);
            }
        }
        
        public static string ActionTypeHasTicketError {
            get {
                return ResourceManager.GetString("ActionTypeHasTicketError", resourceCulture);
            }
        }
        
        public static string ActionTypeIsNull {
            get {
                return ResourceManager.GetString("ActionTypeIsNull", resourceCulture);
            }
        }
        
        public static string ActionTypeNameRequired {
            get {
                return ResourceManager.GetString("ActionTypeNameRequired", resourceCulture);
            }
        }
        
        public static string ActionTypeNotFound {
            get {
                return ResourceManager.GetString("ActionTypeNotFound", resourceCulture);
            }
        }
        
        public static string ActionTypeSelectedError {
            get {
                return ResourceManager.GetString("ActionTypeSelectedError", resourceCulture);
            }
        }
        
        public static string AlbumSelect {
            get {
                return ResourceManager.GetString("AlbumSelect", resourceCulture);
            }
        }
        
        public static string AnswerChangeStatusTicket {
            get {
                return ResourceManager.GetString("AnswerChangeStatusTicket", resourceCulture);
            }
        }
        
        public static string AnswerForThisReferenceNotFound {
            get {
                return ResourceManager.GetString("AnswerForThisReferenceNotFound", resourceCulture);
            }
        }
        
        public static string AttachFormat {
            get {
                return ResourceManager.GetString("AttachFormat", resourceCulture);
            }
        }
        
        public static string CategoryNameRequired {
            get {
                return ResourceManager.GetString("CategoryNameRequired", resourceCulture);
            }
        }
        
        public static string CategoryNotFound {
            get {
                return ResourceManager.GetString("CategoryNotFound", resourceCulture);
            }
        }
        
        public static string CategorySelectedError {
            get {
                return ResourceManager.GetString("CategorySelectedError", resourceCulture);
            }
        }
        
        public static string CompanyIsDeleted {
            get {
                return ResourceManager.GetString("CompanyIsDeleted", resourceCulture);
            }
        }
        
        public static string CreateDateFormat {
            get {
                return ResourceManager.GetString("CreateDateFormat", resourceCulture);
            }
        }
        
        public static string CreateSuccessMessage {
            get {
                return ResourceManager.GetString("CreateSuccessMessage", resourceCulture);
            }
        }
        
        public static string CustomerExpiredError {
            get {
                return ResourceManager.GetString("CustomerExpiredError", resourceCulture);
            }
        }
        
        public static string CustomerHasMappingError {
            get {
                return ResourceManager.GetString("CustomerHasMappingError", resourceCulture);
            }
        }
        
        public static string CustomerHasprojectError {
            get {
                return ResourceManager.GetString("CustomerHasprojectError", resourceCulture);
            }
        }
        
        public static string CustomerHasUserError {
            get {
                return ResourceManager.GetString("CustomerHasUserError", resourceCulture);
            }
        }
        
        public static string CustomerNotActiveError {
            get {
                return ResourceManager.GetString("CustomerNotActiveError", resourceCulture);
            }
        }
        
        public static string CustomerNotExist {
            get {
                return ResourceManager.GetString("CustomerNotExist", resourceCulture);
            }
        }
        
        public static string CustomerNotFound {
            get {
                return ResourceManager.GetString("CustomerNotFound", resourceCulture);
            }
        }
        
        public static string CustomerOrCompanyIsNull {
            get {
                return ResourceManager.GetString("CustomerOrCompanyIsNull", resourceCulture);
            }
        }
        
        public static string CustomerSelectedError {
            get {
                return ResourceManager.GetString("CustomerSelectedError", resourceCulture);
            }
        }
        
        public static string DateConflictError {
            get {
                return ResourceManager.GetString("DateConflictError", resourceCulture);
            }
        }
        
        public static string DateFormat {
            get {
                return ResourceManager.GetString("DateFormat", resourceCulture);
            }
        }
        
        public static string DateOfOperation {
            get {
                return ResourceManager.GetString("DateOfOperation", resourceCulture);
            }
        }
        
        public static string DegreeOfEducation {
            get {
                return ResourceManager.GetString("DegreeOfEducation", resourceCulture);
            }
        }
        
        public static string DeleteMessageSuccess {
            get {
                return ResourceManager.GetString("DeleteMessageSuccess", resourceCulture);
            }
        }
        
        public static string DescriptionIsRequired {
            get {
                return ResourceManager.GetString("DescriptionIsRequired", resourceCulture);
            }
        }
        
        public static string DigitFormat {
            get {
                return ResourceManager.GetString("DigitFormat", resourceCulture);
            }
        }
        
        public static string DiscountCode {
            get {
                return ResourceManager.GetString("DiscountCode", resourceCulture);
            }
        }
        
        public static string EditError {
            get {
                return ResourceManager.GetString("EditError", resourceCulture);
            }
        }
        
        public static string EditSuccess {
            get {
                return ResourceManager.GetString("EditSuccess", resourceCulture);
            }
        }
        
        public static string EmailFormat {
            get {
                return ResourceManager.GetString("EmailFormat", resourceCulture);
            }
        }
        
        public static string EmailHelp {
            get {
                return ResourceManager.GetString("EmailHelp", resourceCulture);
            }
        }
        
        public static string EmploymentStatus {
            get {
                return ResourceManager.GetString("EmploymentStatus", resourceCulture);
            }
        }
        
        public static string EmpttyTitle {
            get {
                return ResourceManager.GetString("EmpttyTitle", resourceCulture);
            }
        }
        
        public static string EmptyAnswer {
            get {
                return ResourceManager.GetString("EmptyAnswer", resourceCulture);
            }
        }
        
        public static string EmptyEmail {
            get {
                return ResourceManager.GetString("EmptyEmail", resourceCulture);
            }
        }
        
        public static string EmptyFields {
            get {
                return ResourceManager.GetString("EmptyFields", resourceCulture);
            }
        }
        
        public static string EmptyFile {
            get {
                return ResourceManager.GetString("EmptyFile", resourceCulture);
            }
        }
        
        public static string Emptyheight {
            get {
                return ResourceManager.GetString("Emptyheight", resourceCulture);
            }
        }
        
        public static string EmptyLesson {
            get {
                return ResourceManager.GetString("EmptyLesson", resourceCulture);
            }
        }
        
        public static string EmptyPoll {
            get {
                return ResourceManager.GetString("EmptyPoll", resourceCulture);
            }
        }
        
        public static string EmptyQuestion {
            get {
                return ResourceManager.GetString("EmptyQuestion", resourceCulture);
            }
        }
        
        public static string EmptySection {
            get {
                return ResourceManager.GetString("EmptySection", resourceCulture);
            }
        }
        
        public static string EmptyText {
            get {
                return ResourceManager.GetString("EmptyText", resourceCulture);
            }
        }
        
        public static string EmptyTitle {
            get {
                return ResourceManager.GetString("EmptyTitle", resourceCulture);
            }
        }
        
        public static string EmptyUniversity {
            get {
                return ResourceManager.GetString("EmptyUniversity", resourceCulture);
            }
        }
        
        public static string EmptyWidth {
            get {
                return ResourceManager.GetString("EmptyWidth", resourceCulture);
            }
        }
        
        public static string ErrorCompare {
            get {
                return ResourceManager.GetString("ErrorCompare", resourceCulture);
            }
        }
        
        public static string ErrorLogin {
            get {
                return ResourceManager.GetString("ErrorLogin", resourceCulture);
            }
        }
        
        public static string ErrorPathFile {
            get {
                return ResourceManager.GetString("ErrorPathFile", resourceCulture);
            }
        }
        
        public static string ErrorRequired {
            get {
                return ResourceManager.GetString("ErrorRequired", resourceCulture);
            }
        }
        
        public static string ErrorSizeFile {
            get {
                return ResourceManager.GetString("ErrorSizeFile", resourceCulture);
            }
        }
        
        public static string ErroZiroByteFile {
            get {
                return ResourceManager.GetString("ErroZiroByteFile", resourceCulture);
            }
        }
        
        public static string ExpireDateFormat {
            get {
                return ResourceManager.GetString("ExpireDateFormat", resourceCulture);
            }
        }
        
        public static string FamilyEmpty {
            get {
                return ResourceManager.GetString("FamilyEmpty", resourceCulture);
            }
        }
        
        public static string FAQCategorySelectedError {
            get {
                return ResourceManager.GetString("FAQCategorySelectedError", resourceCulture);
            }
        }
        
        public static string FAQIsNull {
            get {
                return ResourceManager.GetString("FAQIsNull", resourceCulture);
            }
        }
        
        public static string FAQNotFoundError {
            get {
                return ResourceManager.GetString("FAQNotFoundError", resourceCulture);
            }
        }
        
        public static string FieldOfStudy {
            get {
                return ResourceManager.GetString("FieldOfStudy", resourceCulture);
            }
        }
        
        public static string File1MBError {
            get {
                return ResourceManager.GetString("File1MBError", resourceCulture);
            }
        }
        
        public static string FileEmpty {
            get {
                return ResourceManager.GetString("FileEmpty", resourceCulture);
            }
        }
        
        public static string FileError_SelectNewFile {
            get {
                return ResourceManager.GetString("FileError_SelectNewFile", resourceCulture);
            }
        }
        
        public static string FileExtensionError {
            get {
                return ResourceManager.GetString("FileExtensionError", resourceCulture);
            }
        }
        
        public static string FileSelect {
            get {
                return ResourceManager.GetString("FileSelect", resourceCulture);
            }
        }
        
        public static string FindUserIdFailed {
            get {
                return ResourceManager.GetString("FindUserIdFailed", resourceCulture);
            }
        }
        
        public static string FixedLengthError {
            get {
                return ResourceManager.GetString("FixedLengthError", resourceCulture);
            }
        }
        
        public static string ForOrdering {
            get {
                return ResourceManager.GetString("ForOrdering", resourceCulture);
            }
        }
        
        public static string GifOnly {
            get {
                return ResourceManager.GetString("GifOnly", resourceCulture);
            }
        }
        
        public static string GroupEmpty {
            get {
                return ResourceManager.GetString("GroupEmpty", resourceCulture);
            }
        }
        
        public static string GroupHasMappingError {
            get {
                return ResourceManager.GetString("GroupHasMappingError", resourceCulture);
            }
        }
        
        public static string GroupHasUserError {
            get {
                return ResourceManager.GetString("GroupHasUserError", resourceCulture);
            }
        }
        
        public static string GroupIsNull {
            get {
                return ResourceManager.GetString("GroupIsNull", resourceCulture);
            }
        }
        
        public static string GroupNotExist {
            get {
                return ResourceManager.GetString("GroupNotExist", resourceCulture);
            }
        }
        
        public static string GroupNotFound {
            get {
                return ResourceManager.GetString("GroupNotFound", resourceCulture);
            }
        }
        
        public static string GroupRelationIsNull {
            get {
                return ResourceManager.GetString("GroupRelationIsNull", resourceCulture);
            }
        }
        
        public static string GroupSelectError {
            get {
                return ResourceManager.GetString("GroupSelectError", resourceCulture);
            }
        }
        
        public static string ImgFormat {
            get {
                return ResourceManager.GetString("ImgFormat", resourceCulture);
            }
        }
        
        public static string ImgSize {
            get {
                return ResourceManager.GetString("ImgSize", resourceCulture);
            }
        }
        
        public static string IsNullMessages {
            get {
                return ResourceManager.GetString("IsNullMessages", resourceCulture);
            }
        }
        
        public static string IsNullWarning {
            get {
                return ResourceManager.GetString("IsNullWarning", resourceCulture);
            }
        }
        
        public static string ItemNotFound {
            get {
                return ResourceManager.GetString("ItemNotFound", resourceCulture);
            }
        }
        
        public static string LastNameRequired {
            get {
                return ResourceManager.GetString("LastNameRequired", resourceCulture);
            }
        }
        
        public static string LinkFormat {
            get {
                return ResourceManager.GetString("LinkFormat", resourceCulture);
            }
        }
        
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        public static string LogOutedMessage {
            get {
                return ResourceManager.GetString("LogOutedMessage", resourceCulture);
            }
        }
        
        public static string LogOutFromAccount {
            get {
                return ResourceManager.GetString("LogOutFromAccount", resourceCulture);
            }
        }
        
        public static string LogOutFromAccount1 {
            get {
                return ResourceManager.GetString("LogOutFromAccount1", resourceCulture);
            }
        }
        
        public static string MappingNotFound {
            get {
                return ResourceManager.GetString("MappingNotFound", resourceCulture);
            }
        }
        
        public static string MappingOwnerCompanyNotFound {
            get {
                return ResourceManager.GetString("MappingOwnerCompanyNotFound", resourceCulture);
            }
        }
        
        public static string MaritalStatus {
            get {
                return ResourceManager.GetString("MaritalStatus", resourceCulture);
            }
        }
        
        public static string MaximumSize1MB {
            get {
                return ResourceManager.GetString("MaximumSize1MB", resourceCulture);
            }
        }
        
        public static string MaxLengthError {
            get {
                return ResourceManager.GetString("MaxLengthError", resourceCulture);
            }
        }
        
        public static string MaxSize500000 {
            get {
                return ResourceManager.GetString("MaxSize500000", resourceCulture);
            }
        }
        
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        public static string MinTicketCountError {
            get {
                return ResourceManager.GetString("MinTicketCountError", resourceCulture);
            }
        }
        
        public static string MobileError {
            get {
                return ResourceManager.GetString("MobileError", resourceCulture);
            }
        }
        
        public static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        public static string NationalCodeError {
            get {
                return ResourceManager.GetString("NationalCodeError", resourceCulture);
            }
        }
        
        public static string NotAccessToAdminGroup {
            get {
                return ResourceManager.GetString("NotAccessToAdminGroup", resourceCulture);
            }
        }
        
        public static string NotAccessToPageConnectToCompany {
            get {
                return ResourceManager.GetString("NotAccessToPageConnectToCompany", resourceCulture);
            }
        }
        
        public static string NotFoundError {
            get {
                return ResourceManager.GetString("NotFoundError", resourceCulture);
            }
        }
        
        public static string NumberRange {
            get {
                return ResourceManager.GetString("NumberRange", resourceCulture);
            }
        }
        
        public static string PasswordConfirmRequired {
            get {
                return ResourceManager.GetString("PasswordConfirmRequired", resourceCulture);
            }
        }
        
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        public static string Password_PasswordConfirmError {
            get {
                return ResourceManager.GetString("Password_PasswordConfirmError", resourceCulture);
            }
        }
        
        public static string PhoneError {
            get {
                return ResourceManager.GetString("PhoneError", resourceCulture);
            }
        }
        
        public static string PhoneNumberStartWithError {
            get {
                return ResourceManager.GetString("PhoneNumberStartWithError", resourceCulture);
            }
        }
        
        public static string PleaseLoginInSite {
            get {
                return ResourceManager.GetString("PleaseLoginInSite", resourceCulture);
            }
        }
        
        public static string PostEmpty {
            get {
                return ResourceManager.GetString("PostEmpty", resourceCulture);
            }
        }
        
        public static string PostNotExistError {
            get {
                return ResourceManager.GetString("PostNotExistError", resourceCulture);
            }
        }
        
        public static string PostTypeInitialIsNotWorking {
            get {
                return ResourceManager.GetString("PostTypeInitialIsNotWorking", resourceCulture);
            }
        }
        
        public static string ProjectHasGroup {
            get {
                return ResourceManager.GetString("ProjectHasGroup", resourceCulture);
            }
        }
        
        public static string ProjectHasMapping {
            get {
                return ResourceManager.GetString("ProjectHasMapping", resourceCulture);
            }
        }
        
        public static string ProjectHasSubSystemError {
            get {
                return ResourceManager.GetString("ProjectHasSubSystemError", resourceCulture);
            }
        }
        
        public static string ProjectIsNull {
            get {
                return ResourceManager.GetString("ProjectIsNull", resourceCulture);
            }
        }
        
        public static string ProjectNameRequired {
            get {
                return ResourceManager.GetString("ProjectNameRequired", resourceCulture);
            }
        }
        
        public static string ProjectNotExist {
            get {
                return ResourceManager.GetString("ProjectNotExist", resourceCulture);
            }
        }
        
        public static string ProjectNotFound {
            get {
                return ResourceManager.GetString("ProjectNotFound", resourceCulture);
            }
        }
        
        public static string ProjectSelectedError {
            get {
                return ResourceManager.GetString("ProjectSelectedError", resourceCulture);
            }
        }
        
        public static string QuestionDelete {
            get {
                return ResourceManager.GetString("QuestionDelete", resourceCulture);
            }
        }
        
        public static string QuestionEmpty {
            get {
                return ResourceManager.GetString("QuestionEmpty", resourceCulture);
            }
        }
        
        public static string QuestionUpdate {
            get {
                return ResourceManager.GetString("QuestionUpdate", resourceCulture);
            }
        }
        
        public static string QueueSentTicketIsFull {
            get {
                return ResourceManager.GetString("QueueSentTicketIsFull", resourceCulture);
            }
        }
        
        public static string RangeFieldError {
            get {
                return ResourceManager.GetString("RangeFieldError", resourceCulture);
            }
        }
        
        public static string RangNo1000 {
            get {
                return ResourceManager.GetString("RangNo1000", resourceCulture);
            }
        }
        
        public static string RangUnit {
            get {
                return ResourceManager.GetString("RangUnit", resourceCulture);
            }
        }
        
        public static string ReferenceIsSeccess {
            get {
                return ResourceManager.GetString("ReferenceIsSeccess", resourceCulture);
            }
        }
        
        public static string ReferenceTicketWithSaveAnswer {
            get {
                return ResourceManager.GetString("ReferenceTicketWithSaveAnswer", resourceCulture);
            }
        }
        
        public static string RelationIsActiveError {
            get {
                return ResourceManager.GetString("RelationIsActiveError", resourceCulture);
            }
        }
        
        public static string ReportIsDeleted {
            get {
                return ResourceManager.GetString("ReportIsDeleted", resourceCulture);
            }
        }
        
        public static string ReportIsNull {
            get {
                return ResourceManager.GetString("ReportIsNull", resourceCulture);
            }
        }
        
        public static string ReportNotFound {
            get {
                return ResourceManager.GetString("ReportNotFound", resourceCulture);
            }
        }
        
        public static string RequestNotValid {
            get {
                return ResourceManager.GetString("RequestNotValid", resourceCulture);
            }
        }
        
        public static string RequiredError {
            get {
                return ResourceManager.GetString("RequiredError", resourceCulture);
            }
        }
        
        public static string RoleNameRequired {
            get {
                return ResourceManager.GetString("RoleNameRequired", resourceCulture);
            }
        }
        
        public static string RoleNotExist {
            get {
                return ResourceManager.GetString("RoleNotExist", resourceCulture);
            }
        }
        
        public static string RoleNotFound {
            get {
                return ResourceManager.GetString("RoleNotFound", resourceCulture);
            }
        }
        
        public static string RoleSelectedError {
            get {
                return ResourceManager.GetString("RoleSelectedError", resourceCulture);
            }
        }
        
        public static string RoleTitleRequired {
            get {
                return ResourceManager.GetString("RoleTitleRequired", resourceCulture);
            }
        }
        
        public static string SaveError {
            get {
                return ResourceManager.GetString("SaveError", resourceCulture);
            }
        }
        
        public static string SaveSuccess {
            get {
                return ResourceManager.GetString("SaveSuccess", resourceCulture);
            }
        }
        
        public static string SaveTicketToReport {
            get {
                return ResourceManager.GetString("SaveTicketToReport", resourceCulture);
            }
        }
        
        public static string SaveTicketWhenCountFAQZiro {
            get {
                return ResourceManager.GetString("SaveTicketWhenCountFAQZiro", resourceCulture);
            }
        }
        
        public static string SearchInFAQ {
            get {
                return ResourceManager.GetString("SearchInFAQ", resourceCulture);
            }
        }
        
        public static string SearchResultIsNull {
            get {
                return ResourceManager.GetString("SearchResultIsNull", resourceCulture);
            }
        }
        
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        public static string SelectedCategoryError {
            get {
                return ResourceManager.GetString("SelectedCategoryError", resourceCulture);
            }
        }
        
        public static string SelectedFieldRequired {
            get {
                return ResourceManager.GetString("SelectedFieldRequired", resourceCulture);
            }
        }
        
        public static string SelectedSubSystemError {
            get {
                return ResourceManager.GetString("SelectedSubSystemError", resourceCulture);
            }
        }
        
        public static string SelectedUserPriotryError {
            get {
                return ResourceManager.GetString("SelectedUserPriotryError", resourceCulture);
            }
        }
        
        public static string SelectItem {
            get {
                return ResourceManager.GetString("SelectItem", resourceCulture);
            }
        }
        
        public static string SelectSubSystemOrProjectError {
            get {
                return ResourceManager.GetString("SelectSubSystemOrProjectError", resourceCulture);
            }
        }
        
        public static string SelectTrueOptionUsers {
            get {
                return ResourceManager.GetString("SelectTrueOptionUsers", resourceCulture);
            }
        }
        
        public static string SelectUserGroupProjectOrUserFromProjectSelected {
            get {
                return ResourceManager.GetString("SelectUserGroupProjectOrUserFromProjectSelected", resourceCulture);
            }
        }
        
        public static string SendCodeFail {
            get {
                return ResourceManager.GetString("SendCodeFail", resourceCulture);
            }
        }
        
        public static string SendCodeSuccess {
            get {
                return ResourceManager.GetString("SendCodeSuccess", resourceCulture);
            }
        }
        
        public static string ServerReqestError {
            get {
                return ResourceManager.GetString("ServerReqestError", resourceCulture);
            }
        }
        
        public static string ShowProfilePage {
            get {
                return ResourceManager.GetString("ShowProfilePage", resourceCulture);
            }
        }
        
        public static string SiteTitle {
            get {
                return ResourceManager.GetString("SiteTitle", resourceCulture);
            }
        }
        
        public static string StatusTicketNotFound {
            get {
                return ResourceManager.GetString("StatusTicketNotFound", resourceCulture);
            }
        }
        
        public static string SubSystemHasTicketError {
            get {
                return ResourceManager.GetString("SubSystemHasTicketError", resourceCulture);
            }
        }
        
        public static string SubSystemIsNull {
            get {
                return ResourceManager.GetString("SubSystemIsNull", resourceCulture);
            }
        }
        
        public static string SubSystemNameRequired {
            get {
                return ResourceManager.GetString("SubSystemNameRequired", resourceCulture);
            }
        }
        
        public static string SubSystemNotExist {
            get {
                return ResourceManager.GetString("SubSystemNotExist", resourceCulture);
            }
        }
        
        public static string SubSystemNotFound {
            get {
                return ResourceManager.GetString("SubSystemNotFound", resourceCulture);
            }
        }
        
        public static string SubsystemSelectedError {
            get {
                return ResourceManager.GetString("SubsystemSelectedError", resourceCulture);
            }
        }
        
        public static string SuccessLoginMessage {
            get {
                return ResourceManager.GetString("SuccessLoginMessage", resourceCulture);
            }
        }
        
        public static string SupportManagmentGroupInCustomerNotFound {
            get {
                return ResourceManager.GetString("SupportManagmentGroupInCustomerNotFound", resourceCulture);
            }
        }
        
        public static string SystemError {
            get {
                return ResourceManager.GetString("SystemError", resourceCulture);
            }
        }
        
        public static string SystemErrorReLogin {
            get {
                return ResourceManager.GetString("SystemErrorReLogin", resourceCulture);
            }
        }
        
        public static string SystemError_TryAgain {
            get {
                return ResourceManager.GetString("SystemError_TryAgain", resourceCulture);
            }
        }
        
        public static string TestNewPasswordError {
            get {
                return ResourceManager.GetString("TestNewPasswordError", resourceCulture);
            }
        }
        
        public static string TextFormat {
            get {
                return ResourceManager.GetString("TextFormat", resourceCulture);
            }
        }
        
        public static string ThisNameIsExist {
            get {
                return ResourceManager.GetString("ThisNameIsExist", resourceCulture);
            }
        }
        
        public static string ThisRelationIsExist {
            get {
                return ResourceManager.GetString("ThisRelationIsExist", resourceCulture);
            }
        }
        
        public static string TicketNotFound {
            get {
                return ResourceManager.GetString("TicketNotFound", resourceCulture);
            }
        }
        
        public static string TicketReferenceForTicketNotSet {
            get {
                return ResourceManager.GetString("TicketReferenceForTicketNotSet", resourceCulture);
            }
        }
        
        public static string TicketReferenceNotExist {
            get {
                return ResourceManager.GetString("TicketReferenceNotExist", resourceCulture);
            }
        }
        
        public static string TicketTypeIsRequired {
            get {
                return ResourceManager.GetString("TicketTypeIsRequired", resourceCulture);
            }
        }
        
        public static string TicketTypeNotFound {
            get {
                return ResourceManager.GetString("TicketTypeNotFound", resourceCulture);
            }
        }
        
        public static string TimeOfOperation {
            get {
                return ResourceManager.GetString("TimeOfOperation", resourceCulture);
            }
        }
        
        public static string TimeOutSendCodeError {
            get {
                return ResourceManager.GetString("TimeOutSendCodeError", resourceCulture);
            }
        }
        
        public static string TitleIsRequired {
            get {
                return ResourceManager.GetString("TitleIsRequired", resourceCulture);
            }
        }
        
        public static string UpdateMessageSuccess {
            get {
                return ResourceManager.GetString("UpdateMessageSuccess", resourceCulture);
            }
        }
        
        public static string UseCustomers {
            get {
                return ResourceManager.GetString("UseCustomers", resourceCulture);
            }
        }
        
        public static string Useprojects {
            get {
                return ResourceManager.GetString("Useprojects", resourceCulture);
            }
        }
        
        public static string UserAddedInListGroup {
            get {
                return ResourceManager.GetString("UserAddedInListGroup", resourceCulture);
            }
        }
        
        public static string UserExistInGroup {
            get {
                return ResourceManager.GetString("UserExistInGroup", resourceCulture);
            }
        }
        
        public static string UserExpiredError {
            get {
                return ResourceManager.GetString("UserExpiredError", resourceCulture);
            }
        }
        
        public static string UserGroupProjectNotFound {
            get {
                return ResourceManager.GetString("UserGroupProjectNotFound", resourceCulture);
            }
        }
        
        public static string UserGroupProjectSelectError {
            get {
                return ResourceManager.GetString("UserGroupProjectSelectError", resourceCulture);
            }
        }
        
        public static string UserHasTicketError {
            get {
                return ResourceManager.GetString("UserHasTicketError", resourceCulture);
            }
        }
        
        public static string UserNameIsExistError {
            get {
                return ResourceManager.GetString("UserNameIsExistError", resourceCulture);
            }
        }
        
        public static string UserNameRequied {
            get {
                return ResourceManager.GetString("UserNameRequied", resourceCulture);
            }
        }
        
        public static string UserNotActiveError {
            get {
                return ResourceManager.GetString("UserNotActiveError", resourceCulture);
            }
        }
        
        public static string UserNotExist {
            get {
                return ResourceManager.GetString("UserNotExist", resourceCulture);
            }
        }
        
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        public static string UserPriotryIsRequired {
            get {
                return ResourceManager.GetString("UserPriotryIsRequired", resourceCulture);
            }
        }
        
        public static string UserPriotryNotFound {
            get {
                return ResourceManager.GetString("UserPriotryNotFound", resourceCulture);
            }
        }
        
        public static string UserPriotryNotSelected {
            get {
                return ResourceManager.GetString("UserPriotryNotSelected", resourceCulture);
            }
        }
        
        public static string UserSelectedCustomer {
            get {
                return ResourceManager.GetString("UserSelectedCustomer", resourceCulture);
            }
        }
        
        public static string UserWithGroupHasTicketReferenceError {
            get {
                return ResourceManager.GetString("UserWithGroupHasTicketReferenceError", resourceCulture);
            }
        }
        
        public static string ViewOnTheMainPage {
            get {
                return ResourceManager.GetString("ViewOnTheMainPage", resourceCulture);
            }
        }
        
        public static string YourAnswerToTicket {
            get {
                return ResourceManager.GetString("YourAnswerToTicket", resourceCulture);
            }
        }
        
        public static string CountFileError {
            get {
                return ResourceManager.GetString("CountFileError", resourceCulture);
            }
        }
        
        public static string VolumeFileError {
            get {
                return ResourceManager.GetString("VolumeFileError", resourceCulture);
            }
        }
        
        public static string PaidBefore {
            get {
                return ResourceManager.GetString("PaidBefore", resourceCulture);
            }
        }
        
        public static string UnAcceptablePrice {
            get {
                return ResourceManager.GetString("UnAcceptablePrice", resourceCulture);
            }
        }
        
        public static string ReturnRequestNotFound {
            get {
                return ResourceManager.GetString("ReturnRequestNotFound", resourceCulture);
            }
        }
        
        public static string ReturnRequestStillNotChecked {
            get {
                return ResourceManager.GetString("ReturnRequestStillNotChecked", resourceCulture);
            }
        }
        
        public static string PaymentCodeNotFound {
            get {
                return ResourceManager.GetString("PaymentCodeNotFound", resourceCulture);
            }
        }
        
        public static string ReturnRequestAccepted {
            get {
                return ResourceManager.GetString("ReturnRequestAccepted", resourceCulture);
            }
        }
        
        public static string ReturnRequestRejected {
            get {
                return ResourceManager.GetString("ReturnRequestRejected", resourceCulture);
            }
        }
        
        public static string ReturnRejectDescriptionNotEnterd {
            get {
                return ResourceManager.GetString("ReturnRejectDescriptionNotEnterd", resourceCulture);
            }
        }
        
        public static string GroupId {
            get {
                return ResourceManager.GetString("GroupId", resourceCulture);
            }
        }
        
        public static string PageSettingDeleted {
            get {
                return ResourceManager.GetString("PageSettingDeleted", resourceCulture);
            }
        }
        
        public static string TableIsEmpty {
            get {
                return ResourceManager.GetString("TableIsEmpty", resourceCulture);
            }
        }
        
        public static string ImageNotExist {
            get {
                return ResourceManager.GetString("ImageNotExist", resourceCulture);
            }
        }
        
        public static string TokenLifeTimeError {
            get {
                return ResourceManager.GetString("TokenLifeTimeError", resourceCulture);
            }
        }
        
        public static string PhoneNumberAndCaptchaError {
            get {
                return ResourceManager.GetString("PhoneNumberAndCaptchaError", resourceCulture);
            }
        }
        
        public static string CaptchaNotFound {
            get {
                return ResourceManager.GetString("CaptchaNotFound", resourceCulture);
            }
        }
        
        public static string BeforeCodeIsActive {
            get {
                return ResourceManager.GetString("BeforeCodeIsActive", resourceCulture);
            }
        }
        
        public static string OtpCodeIsInvalid {
            get {
                return ResourceManager.GetString("OtpCodeIsInvalid", resourceCulture);
            }
        }
        
        public static string LawNotFoundFileError {
            get {
                return ResourceManager.GetString("LawNotFoundFileError", resourceCulture);
            }
        }
        
        public static string ExtensionFileNotFound {
            get {
                return ResourceManager.GetString("ExtensionFileNotFound", resourceCulture);
            }
        }
        
        public static string ExtensionFileNotSupported {
            get {
                return ResourceManager.GetString("ExtensionFileNotSupported", resourceCulture);
            }
        }
        
        public static string DataFound {
            get {
                return ResourceManager.GetString("DataFound", resourceCulture);
            }
        }
        
        public static string Network_Internet_Error {
            get {
                return ResourceManager.GetString("Network_Internet_Error", resourceCulture);
            }
        }
        
        public static string ListRolesIsNotEmpty {
            get {
                return ResourceManager.GetString("ListRolesIsNotEmpty", resourceCulture);
            }
        }
        
        public static string AlreadyAxistsInTheList {
            get {
                return ResourceManager.GetString("AlreadyAxistsInTheList", resourceCulture);
            }
        }
        
        public static string LisIsNotEmpty {
            get {
                return ResourceManager.GetString("LisIsNotEmpty", resourceCulture);
            }
        }
        
        public static string AssemblyCannotBeNull {
            get {
                return ResourceManager.GetString("AssemblyCannotBeNull", resourceCulture);
            }
        }
        
        public static string ServerIsErlyExistButThisServerKeyIsChanged {
            get {
                return ResourceManager.GetString("ServerIsErlyExistButThisServerKeyIsChanged", resourceCulture);
            }
        }
        
        public static string ServerIsCheck {
            get {
                return ResourceManager.GetString("ServerIsCheck", resourceCulture);
            }
        }
        
        public static string TextLoading {
            get {
                return ResourceManager.GetString("TextLoading", resourceCulture);
            }
        }
        
        public static string ForSEO {
            get {
                return ResourceManager.GetString("ForSEO", resourceCulture);
            }
        }
        
        public static string ForWaitMouseOnImage {
            get {
                return ResourceManager.GetString("ForWaitMouseOnImage", resourceCulture);
            }
        }
        
        public static string ConfirmWarning {
            get {
                return ResourceManager.GetString("ConfirmWarning", resourceCulture);
            }
        }
        
        public static string ConfirmMessageSuccess {
            get {
                return ResourceManager.GetString("ConfirmMessageSuccess", resourceCulture);
            }
        }
        
        public static string QuestionDeleteAttachments {
            get {
                return ResourceManager.GetString("QuestionDeleteAttachments", resourceCulture);
            }
        }
        
        public static string CloseAndTryAgain {
            get {
                return ResourceManager.GetString("CloseAndTryAgain", resourceCulture);
            }
        }
        
        public static string CountError {
            get {
                return ResourceManager.GetString("CountError", resourceCulture);
            }
        }
        
        public static string RepeatError {
            get {
                return ResourceManager.GetString("RepeatError", resourceCulture);
            }
        }
        
        public static string WarningToRequestForCheckPrice {
            get {
                return ResourceManager.GetString("WarningToRequestForCheckPrice", resourceCulture);
            }
        }
        
        public static string ChangeStatusSuccess {
            get {
                return ResourceManager.GetString("ChangeStatusSuccess", resourceCulture);
            }
        }
        
        public static string ChangePrice {
            get {
                return ResourceManager.GetString("ChangePrice", resourceCulture);
            }
        }
        
        public static string ErrorPercentValue {
            get {
                return ResourceManager.GetString("ErrorPercentValue", resourceCulture);
            }
        }
        
        public static string MinAndMaxValueFieldError {
            get {
                return ResourceManager.GetString("MinAndMaxValueFieldError", resourceCulture);
            }
        }
        
        public static string ShopAndProductRequired {
            get {
                return ResourceManager.GetString("ShopAndProductRequired", resourceCulture);
            }
        }
        
        public static string ImageSettings {
            get {
                return ResourceManager.GetString("ImageSettings", resourceCulture);
            }
        }
        
        public static string ProductSettings {
            get {
                return ResourceManager.GetString("ProductSettings", resourceCulture);
            }
        }
        
        public static string InformationPriceIsRequired {
            get {
                return ResourceManager.GetString("InformationPriceIsRequired", resourceCulture);
            }
        }
        
        public static string QuestionDeleteOtherImages {
            get {
                return ResourceManager.GetString("QuestionDeleteOtherImages", resourceCulture);
            }
        }
        
        public static string QuestionChangeActivation {
            get {
                return ResourceManager.GetString("QuestionChangeActivation", resourceCulture);
            }
        }
        
        public static string QuestionMoveProductToPriceInquery {
            get {
                return ResourceManager.GetString("QuestionMoveProductToPriceInquery", resourceCulture);
            }
        }
        
        public static string FieldMinValueError {
            get {
                return ResourceManager.GetString("FieldMinValueError", resourceCulture);
            }
        }
        
        public static string FieldConflictError {
            get {
                return ResourceManager.GetString("FieldConflictError", resourceCulture);
            }
        }
        
        public static string UpdateMovedFromCategoryToCategoryMessageSuccess {
            get {
                return ResourceManager.GetString("UpdateMovedFromCategoryToCategoryMessageSuccess", resourceCulture);
            }
        }
        
        public static string SuccessMoveAllProductToRequestCheckPriceMessage {
            get {
                return ResourceManager.GetString("SuccessMoveAllProductToRequestCheckPriceMessage", resourceCulture);
            }
        }
        
        public static string FieldMaxValueError {
            get {
                return ResourceManager.GetString("FieldMaxValueError", resourceCulture);
            }
        }
        
        public static string CreateUserMoneyAssets {
            get {
                return ResourceManager.GetString("CreateUserMoneyAssets", resourceCulture);
            }
        }
        
        public static string CreateUserGoldAssets {
            get {
                return ResourceManager.GetString("CreateUserGoldAssets", resourceCulture);
            }
        }
        
        public static string CreateUserBankAccount {
            get {
                return ResourceManager.GetString("CreateUserBankAccount", resourceCulture);
            }
        }
        
        public static string UserRoundCode {
            get {
                return ResourceManager.GetString("UserRoundCode", resourceCulture);
            }
        }
        
        public static string FirstUserAssetsDescription {
            get {
                return ResourceManager.GetString("FirstUserAssetsDescription", resourceCulture);
            }
        }
        
        public static string NotificationTextDocumentTypeDeposit {
            get {
                return ResourceManager.GetString("NotificationTextDocumentTypeDeposit", resourceCulture);
            }
        }
        
        public static string DocumentForTextDocumentTypeDeposit {
            get {
                return ResourceManager.GetString("DocumentForTextDocumentTypeDeposit", resourceCulture);
            }
        }
        
        public static string DocumentForTextDocumentTypeWithdraw {
            get {
                return ResourceManager.GetString("DocumentForTextDocumentTypeWithdraw", resourceCulture);
            }
        }
        
        public static string NotificationTextDocumentTypeWithdraw {
            get {
                return ResourceManager.GetString("NotificationTextDocumentTypeWithdraw", resourceCulture);
            }
        }
        
        public static string DocumentForTextDocumentTypeBuyNow {
            get {
                return ResourceManager.GetString("DocumentForTextDocumentTypeBuyNow", resourceCulture);
            }
        }
        
        public static string NotificationTextDocumentTypeBuyNow {
            get {
                return ResourceManager.GetString("NotificationTextDocumentTypeBuyNow", resourceCulture);
            }
        }
        
        public static string DocumentForTextDocumentTypeSellNow {
            get {
                return ResourceManager.GetString("DocumentForTextDocumentTypeSellNow", resourceCulture);
            }
        }
        
        public static string NotificationTextDocumentTypeSellNow {
            get {
                return ResourceManager.GetString("NotificationTextDocumentTypeSellNow", resourceCulture);
            }
        }
        
        public static string DocumentForTextDocumentTypeReferal {
            get {
                return ResourceManager.GetString("DocumentForTextDocumentTypeReferal", resourceCulture);
            }
        }
        
        public static string NotificationTextDocumentTypeReferal {
            get {
                return ResourceManager.GetString("NotificationTextDocumentTypeReferal", resourceCulture);
            }
        }
    }
}
