//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PageTitles {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PageTitles() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Resources.PageTitles", typeof(PageTitles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        public static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        public static string AdminSettings {
            get {
                return ResourceManager.GetString("AdminSettings", resourceCulture);
            }
        }
        
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        public static string CreateMenuItem {
            get {
                return ResourceManager.GetString("CreateMenuItem", resourceCulture);
            }
        }
        
        public static string CreatePage {
            get {
                return ResourceManager.GetString("CreatePage", resourceCulture);
            }
        }
        
        public static string CreateRole {
            get {
                return ResourceManager.GetString("CreateRole", resourceCulture);
            }
        }
        
        public static string CreateUser {
            get {
                return ResourceManager.GetString("CreateUser", resourceCulture);
            }
        }
        
        public static string DeactivateAccount {
            get {
                return ResourceManager.GetString("DeactivateAccount", resourceCulture);
            }
        }
        
        public static string DeleteMenuItem {
            get {
                return ResourceManager.GetString("DeleteMenuItem", resourceCulture);
            }
        }
        
        public static string DeletePage {
            get {
                return ResourceManager.GetString("DeletePage", resourceCulture);
            }
        }
        
        public static string DeleteRole {
            get {
                return ResourceManager.GetString("DeleteRole", resourceCulture);
            }
        }
        
        public static string DeleteUser {
            get {
                return ResourceManager.GetString("DeleteUser", resourceCulture);
            }
        }
        
        public static string Error404 {
            get {
                return ResourceManager.GetString("Error404", resourceCulture);
            }
        }
        
        public static string Error500 {
            get {
                return ResourceManager.GetString("Error500", resourceCulture);
            }
        }
        
        public static string FileManager {
            get {
                return ResourceManager.GetString("FileManager", resourceCulture);
            }
        }
        
        public static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        public static string MenuItemDetails {
            get {
                return ResourceManager.GetString("MenuItemDetails", resourceCulture);
            }
        }
        
        public static string MenuItemManagement {
            get {
                return ResourceManager.GetString("MenuItemManagement", resourceCulture);
            }
        }
        
        public static string PageDetails {
            get {
                return ResourceManager.GetString("PageDetails", resourceCulture);
            }
        }
        
        public static string PageManagement {
            get {
                return ResourceManager.GetString("PageManagement", resourceCulture);
            }
        }
        
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        public static string RoleDetails {
            get {
                return ResourceManager.GetString("RoleDetails", resourceCulture);
            }
        }
        
        public static string RoleManagement {
            get {
                return ResourceManager.GetString("RoleManagement", resourceCulture);
            }
        }
        
        public static string TerminateAccount {
            get {
                return ResourceManager.GetString("TerminateAccount", resourceCulture);
            }
        }
        
        public static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
        
        public static string UpdateMenuItem {
            get {
                return ResourceManager.GetString("UpdateMenuItem", resourceCulture);
            }
        }
        
        public static string UpdatePage {
            get {
                return ResourceManager.GetString("UpdatePage", resourceCulture);
            }
        }
        
        public static string UpdateProfile {
            get {
                return ResourceManager.GetString("UpdateProfile", resourceCulture);
            }
        }
        
        public static string UpdateRole {
            get {
                return ResourceManager.GetString("UpdateRole", resourceCulture);
            }
        }
        
        public static string UpdateUser {
            get {
                return ResourceManager.GetString("UpdateUser", resourceCulture);
            }
        }
        
        public static string UserDetails {
            get {
                return ResourceManager.GetString("UserDetails", resourceCulture);
            }
        }
        
        public static string UserManagement {
            get {
                return ResourceManager.GetString("UserManagement", resourceCulture);
            }
        }
        
        public static string UserSettings {
            get {
                return ResourceManager.GetString("UserSettings", resourceCulture);
            }
        }
        
        public static string ValueOfAttribute {
            get {
                return ResourceManager.GetString("ValueOfAttribute", resourceCulture);
            }
        }
        
        public static string NotificationSettings {
            get {
                return ResourceManager.GetString("NotificationSettings", resourceCulture);
            }
        }
        
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        public static string NotificationType {
            get {
                return ResourceManager.GetString("NotificationType", resourceCulture);
            }
        }
        
        public static string ListProducts {
            get {
                return ResourceManager.GetString("ListProducts", resourceCulture);
            }
        }
        
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
    }
}
